# Generated by Django 5.0.1 on 2024-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceIt', '0002_alter_cell_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('field', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('profile_picture', models.ImageField(null=True, upload_to='frontend/src/assets/Expert_imgs')),
            ],
        ),
    ]
