# Generated by Django 5.0.1 on 2024-03-13 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AceIt', '0005_alter_expert_about_me_alter_expert_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
